spring:
  datasource:
    url: jdbc:mysql://localhost:10086/stool_base?useSSL=false
  consts:
    front-end-host: https://sunyujun.com
logging:
  config: classpath:logback.xml
  level:
    com.sunyujun: info